# Generated by Django 4.2 on 2023-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_board', models.TextField()),
                ('computer_has_used_submarine_ability', models.BooleanField(default=False)),
                ('computer_has_used_aircraft_carrier_ability', models.BooleanField(default=False)),
                ('player_board', models.TextField()),
                ('player_has_used_submarine_ability', models.BooleanField(default=False)),
                ('player_has_used_aircraft_carrier_ability', models.BooleanField(default=False)),
                ('submarine_count', models.IntegerField()),
                ('aircraft_carrier_count', models.IntegerField()),
                ('destroyer_count', models.IntegerField()),
                ('frigate_count', models.IntegerField()),
                ('battleship_count', models.IntegerField()),
                ('supply_ship_count', models.IntegerField()),
            ],
        ),
    ]
