# Generated by Django 4.2 on 2023-04-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='supply_ship_count',
            new_name='supply_boat_count',
        ),
    ]
