# Generated by Django 4.2 on 2023-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_supply_ship_count_game_supply_boat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='aircraft_carrier_health',
            field=models.IntegerField(default=10),
        ),
    ]
