# Generated by Django 4.2 on 2023-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_aircraft_carrier_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='computer_board',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_board',
            field=models.JSONField(),
        ),
    ]
